title: AWS Config Disabling Channel/Recorder 
id: 07330162-dba1-4746-8121-a9647d49d297
status: test
description: Detects AWS Config Service disabling (taken from sigma/rules/cloud/aws/aws_config_disable_recording.yml)
author: vitaliy0x1
date: 2020/01/21
modified: 2022/10/09
tags:
    - attack.defense_evasion
    - attack.t1562.001
logsource:
    product: aws
    service: cloudtrail 
detection:
    splunk: |
        index=aws sourcetype=cloudtrail eventSource=config.amazonaws.com eventName IN (DeleteDeliveryChannel, StopConfigurationRecorder)
falsepositives:
    - Valid change in AWS Config Service
level: high
